version: "3"
services:
    db:
      image: mysql:latest
      container_name: "Bank_App_Db"
      ports:
        - "33006:3306"
      cap_add:
        - SYS_NICE
      environment:
        MYSQL_ROOT_PASSWORD: s3cr37
        MYSQL_DATABASE: BankApp